export const Urls = {
    ABOUT: "/about",
    HOME: "/",
    BLOGS: "/blogs",
    CONTACT: "/contact",
    SERVICES: "/services",
    RESOURCES: "/resources",
    PASSWORDRESET: "/password-reset",
    PASSWORDRESETSUCCESS: "/password-reset/success",
    LOGIN: "/login",
    SIGNUP: "/sign-up",
    PLAYERSIGNUP: "/sign-up?type=player",
    SCOUTSIGNUP: "/sign-up?type=scout",
    COACHSIGNUP: "/sign-up?type=coach",
}